<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'templado\\mappers\\domdocumentmapper' => '/xml/DomDocumentMapper.php',
                'templado\\mappers\\jsonmapper' => '/json/JsonMapper.php',
                'templado\\mappers\\jsonmapperexception' => '/json/JsonMapperException.php',
                'templado\\mappers\\viewmodel' => '/ViewModel.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    true
);
// @codeCoverageIgnoreEnd
